<!DOCTYPE html>
<html lang="en">
<head>
    <!-- META TAGS -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- TITLE -->
    <title>Měření skoku</title>

    <!-- CSS STYLES -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <a href="#" class="navbar-brand">Měření skoku</a>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm-7">
            <div class="main-section">
                <!-- Form which disappears after submit -->
                <form action="/" class="form-horizontal form-section">
                    <div class="form-group">
                        <label for="firstName" class="col-sm-3 control-label">Jméno:</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="firstName" placeholder="Jméno">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="surName" class="col-sm-3 control-label">Příjmení:</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="surName" placeholder="Příjmení">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">Email:</label>
                        <div class="col-sm-7">
                            <input type="email" class="form-control" id="email" placeholder="Email">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="tel" class="col-sm-3 control-label">Telefon:</label>
                        <div class="col-sm-7">
                            <div class="input-group">
                                <div class="input-group-addon"><span class="glyphicon glyphicon-earphone"></span></div>
                                <input type="text" class="form-control" id="tel" placeholder="Telefon">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="sex" class="col-sm-3 control-label">Pohlaví:</label>
                        <div class="col-sm-7">
                            <select class="form-control" id="sex">
                                <option>Muž</option>
                                <option>Žena</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3">
                            <a class="btn btn-default submit-button">Odeslat</a>
                        </div>
                    </div>
                </form>
                <!-- end of form -->

                <!-- page with start section -->
                <div class="start-section">
                    <button type="button" class="btn btn-primary btn-lg">Start!</button>
                </div>
                <!-- end of page with start section -->

                <!-- page with time counter -->
                <div class="counter-section">
                    <div class="counter-text">0</div>
                    <a href="index.php" class="btn btn-primary btn-lg back-button">Zpět</a>
                </div>
                <!-- end of page with time counter-->
            </div>

            <div class="search-form">
                <div class="input-group">
                    <input type="text" class="form-control search-field" placeholder="Vyhledat" aria-describedby="searchField">
                    <span class="input-group-addon" id="searchField"><span class="glyphicon glyphicon-search"></span></span>
                </div>
            </div>

            <div class="search-results">
            </div>
        </div>

        <div class="col-sm-3 ladder-section">
            <!-- TOP 10 HERE GENERATED BY JS -->
        </div>
    </div>
</div>

<!-- SCRIPTS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jump.js"></script>
<script src="js/ladder.js"></script>
<script src="js/searchForm.js"></script>
</body>
</html>